# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157LYjQuHlmR3PjA7MUORUbVx6hyg1Fem
"""

import pandas as pd
import numpy as np

df = pd.read_csv(r'/content/SampleSuperstore.csv')
df.head()
df.shape

df.describe

df.info()

df.describe()

df.head(10)

df.isnull().sum().sort_values(ascending=False)

df.nunique()

df['Category'].value_counts()

from sklearn .preprocessing import LabelEncoder
le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])
df['Category'].unique()

df['Region'].value_counts()

df['Region'] = le.fit_transform(df['Region'])
df['Region'].nunique()

df['Segment'].value_counts()

df['Segment'] = le.fit_transform(df['Segment'])
df['Segment'].nunique()

import matplotlib.pyplot as plt
import seaborn as sns

sns.pairplot(df,height= 2.5)

col_study  = ['Postal Code','Sales','Quantity','Discount']

sns.pairplot(df[col_study],height=2.5)
plt.show()

pd.options.display.float_format = '{:,.2f}'.format
df.corr()

df['Sub-Category'].describe()



object_df = df.select_dtypes(include=['object']).copy()
object_df.head()

object_df['Ship Mode'].value_counts()

df["Ship Mode"] = df["Ship Mode"].astype('category')
df.dtypes

df['Ship Mode'] = df['Ship Mode'].cat.codes
df['Ship Mode'].value_counts()

df['Sub-Category'] = le.fit_transform(df['Sub-Category'])
df['Sub-Category'].nunique()

df.dtypes

object_df['City'].nunique()

df['State'].nunique()

# df.plot.hist(subplots=True, layout=(2,2), figsize=(10, 10), bins=20)

col_study1 = ['Ship Mode','Segment','Postal Code','Region','Category','Sub-Category','Sales','Quantity','Discount','Profit']
sns.pairplot(df[col_study1],height=2.5)
plt.show()

sns.heatmap(df[col_study1].corr(),annot=True,linewidths=1)

df[col_study1].corr()

df.hist(figsize=(10,15),bins=30)

city_freq = df.groupby('City').size() / (len(df)/100)
city_freq

df.plot(kind='scatter',x='Profit',y='Category')

df['city_encode'] = df['City'].apply(lambda x : city_freq[x])
df['city_encode'].value_counts()

df.dtypes

df.plot(kind='scatter',x='Profit',y='city_encode',alpha=0.8)

sns.pairplot(df[['city_encode','Profit']])

city_freq = df.groupby('State').size() / (len(df)/100)
city_freq

df['State_encode'] = df['State'].apply(lambda x : city_freq[x])
df['State_encode'].value_counts()

df.plot(kind='scatter',x='Profit',y='State_encode')

df.plot(kind='scatter',x='Profit',y='city_encode')

sns.pairplot(df,height=3.5)
plt.show()

